### ISSUE TITLE
Exception in code with nonzero weight!

### ISSUE THREAD

**Issue by idontgetoutmuch** [fzaiser/nonparametric-hmc#1]
```
python3 example_geometric.py
REPETITION 1/10
Running NP-DHMC...
  0%|                                                                   | 0/1100 [00:00<?, ?it/s]Exception in code with nonzero weight!
  0%|                                                                   | 0/1100 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/Users/dom/nonparametric-hmc/example_geometric.py", line 48, in <module>
    run_inference(
  File "/Users/dom/nonparametric-hmc/infer.py", line 397, in run_inference
    samples["hmc"] = run(
  File "/Users/dom/nonparametric-hmc/infer.py", line 386, in run
    results = sampler()
  File "/Users/dom/nonparametric-hmc/infer.py", line 398, in <lambda>
    lambda: np_dhmc(
  File "/Users/dom/nonparametric-hmc/infer.py", line 232, in np_dhmc
    result = integrator_step(run_prog, step * dt, dt, state, state_0)
  File "/Users/dom/nonparametric-hmc/infer.py", line 182, in integrator_step
    result = coord_integrator(
  File "/Users/dom/nonparametric-hmc/infer.py", line 117, in coord_integrator
    new_result = run_prog(q)
  File "/Users/dom/nonparametric-hmc/example_geometric.py", line 49, in <lambda>
    lambda trace: run_prob_prog(geometric, trace=trace),
  File "/Users/dom/nonparametric-hmc/ppl.py", line 205, in run_prob_prog
    raise e
  File "/Users/dom/nonparametric-hmc/ppl.py", line 201, in run_prob_prog
    ret = program(ctx)
  File "/Users/dom/nonparametric-hmc/example_geometric.py", line 15, in geometric
    return 1 + geometric(ctx)
  File "/Users/dom/nonparametric-hmc/example_geometric.py", line 15, in geometric
    return 1 + geometric(ctx)
  File "/Users/dom/nonparametric-hmc/example_geometric.py", line 10, in geometric
    sample = ctx.sample(Uniform(0.0, 1.0), is_cont=False)
  File "/Users/dom/nonparametric-hmc/ppl.py", line 92, in sample
    samples = self.sample_n(1, dist, is_cont)
  File "/Users/dom/nonparametric-hmc/ppl.py", line 124, in sample_n
    self.log_weight = self.log_weight + torch.sum(dist.log_prob(values))
  File "/usr/local/lib/python3.10/site-packages/torch/distributions/uniform.py", line 80, in log_prob
    self._validate_sample(value)
  File "/usr/local/lib/python3.10/site-packages/torch/distributions/distribution.py", line 294, in _validate_sample
    raise ValueError(
ValueError: Expected value argument (Tensor of shape (1,)) to be within the support (Interval(lower_bound=0.0, upper_bound=1.0)) of the distribution Uniform(low: 0.0, high: 1.0), but found invalid values:
tensor([-0.0379286706], grad_fn=<SliceBackward0>)
```

**Comment by idontgetoutmuch** [comment]
With the example program given in the documentation (rather than the geometric example) then the program runs to completion. Beyond that I have not investigated.

```
def simple_prog(ctx: ProbCtx) -> float:
    sample = ctx.sample(torch.distributions.Normal(0., 1.), is_cont=True)
    if sample < 0:
        ctx.score(torch.tensor(0.5))
        return sample.item()
    else:
        return sample.item()

def geometric(ctx: ProbCtx) -> int:
    """Describes a geometric distribution"""
    sample = ctx.sample(Uniform(0.0, 1.0), is_cont=False)
    ctx.constrain(sample, 0.0, 1.0)
    if sample < 0.2:
        return 1
    else:
        return 1 + geometric(ctx)
```

**Comment by fzaiser** [comment]
@idontgetoutmuch What model did you run this on? This exception usually indicates that something is wrong with the probabilistic program you run NP-DHMC on. So it is hard to say what the problem is without knowing more about the probabilistic program you wrote.

In your particular case,

    Expected value argument (Tensor of shape (1,)) to be within the support (Interval(lower_bound=0.0, upper_bound=1.0)) of the distribution Uniform(low: 0.0, high: 1.0), but found invalid values:
    tensor([-0.0379286706], grad_fn=<SliceBackward0>)

looks like you're sampling from a uniform distribution without `ctx.constrain`ing the value to the allowed range. During inference, HMC may proposes samples outside the range, which can lead to an exception like this. Adding  `ctx.constrain(sample, 0.0, 1.0)` in the probabilistic program ensures that such values are discarded (see the geometric example).

Ideally the sampler should recognize this problem itself without the user having to write `ctx.constrain` in the probabilistic program. I'll think about how this could be achieved.

**Comment by idontgetoutmuch** [comment]
Hi @fzaiser I am running this on the model given in `example_geometric.py` (88b7cfa993cab76841c0e7616d1556a5f6c1c015 https://github.com/fzaiser/nonparametric-hmc/blob/main/example_geometric.py#L8):

```
def geometric(ctx: ProbCtx) -> int:
    """Describes a geometric distribution"""
    sample = ctx.sample(Uniform(0.0, 1.0), is_cont=False)
    ctx.constrain(sample, 0.0, 1.0)
    if sample < 0.2:
        return 1
    else:
        return 1 + geometric(ctx)
```

I am guessing it works for you?

**Comment by fzaiser** [comment]
Oh, I did not realize you were talking about the `geometric` example. That one should not produce an error. It worked fine in my tests in the past.

It's not clear to me why this happens. Maybe a newer version of `torch`'s distribution library behaves differently? I'll have to investigate.

Thank you for reporting this!

**Comment by fzaiser** [comment]
Indeed, it seems that `torch`'s distribution code did not verify in the past whether the given value is in the support of the distribution when computing `log_prob`. Now it does the validation in debug mode (not when running `python -O`). I'll work on fixing this now.
